### ISSUE TITLE
dl4jGANInsurance.java  生成器也是生成图片的吗

### ISSUE THREAD

**Issue by mengpengfei** [hamaadshah/gan_deeplearning4j#1]
怎么使用gan生成这种鼠标轨迹[[x,y,t],[x,y,t],[x,y,t],[x,y,t],[x,y,t],[x,y,t]]
能指导下怎么训练，然后拟合人类鼠标滑动轨迹吗

**Comment by hamaadshah** [comment]
嗨：谢谢你的提问。我不熟悉你描述的数据类型，但它似乎非常适合三维张量，就像计算机视觉MNIST数据和我的回购中的合成保险数据一样。我为没有对此提供更多帮助而道歉，但我认为您已经自己回答了问题:)您可以轻松地在repo中为您的特定数据重新编写Java代码。我不相信这样做太难了。祝福，哈马德。

**Comment by mengpengfei** [comment]
thank you very much

**Comment by ggsimida-cw** [comment]
> 如何使用gan生成此类鼠标报表[[x,y,t],[x,y,t],[x,y,t],[x,y,t],[x,y,t],[ x,y,t]] 能指导下怎么训练，然后人体鼠标滑动轨迹吗？

老哥，你好，请问你实现了吗
